# syntax=docker/dockerfile:1

# Stock registry image (same one the stack runs): `kpr gc` shells out
# to its garbage-collect, so collector and store versions match by
# construction. Keep in sync with the registry service in compose.
ARG REGISTRY_IMAGE=registry:3
FROM $REGISTRY_IMAGE AS registry-bin

# Build stage
FROM golang:1.27-alpine AS builder

# Install build dependencies
RUN apk add --no-cache git make

WORKDIR /build

# Copy go mod files first for better caching
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build arguments for version info
ARG VERSION=dev
ARG COMMIT=unknown
ARG BUILD_TIME=unknown

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-w -s \
    -X 'nrtn.dev/catalyst/kpr/internal/config.Version=${VERSION}' \
    -X 'nrtn.dev/catalyst/kpr/internal/config.Commit=${COMMIT}' \
    -X 'nrtn.dev/catalyst/kpr/internal/config.BuildTime=${BUILD_TIME}'" \
    -o kpr ./cmd/app

# Runtime stage
FROM alpine:latest

# Install runtime dependencies (bash: a normal shell for exec-ing
# into the dev stack; sh alone gets old fast)
RUN apk add --no-cache bash ca-certificates tzdata

# Create non-root user
RUN addgroup -g 1000 kpr && \
    adduser -D -u 1000 -G kpr kpr

WORKDIR /app

# Copy binary from builder
COPY --from=builder /build/kpr /usr/local/bin/kpr

# Stock registry binary for `kpr gc`, from the registry-bin stage above.
COPY --from=registry-bin /bin/registry /bin/registry

# License bundle: kpr itself plus third-party attributions
# (THIRD-PARTY.md is generated by `make licenses`).
COPY LICENSE /app/licenses/kpr-GPLv3.txt
COPY LICENSES/ /app/licenses/third-party/

# Set ownership
RUN chown -R kpr:kpr /app

# Switch to non-root user
USER kpr

# Expose ports
EXPOSE 8080 9300

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:9300/health || exit 1

# Default command
CMD ["kpr", "serve"]
