global:
  scrape_interval: 5s

scrape_configs:
  - job_name: kpr
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["kpr:9300"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
