#!/bin/bash
# Regenerate LICENSES/THIRD-PARTY.md from the modules actually
# linked into the kpr binary (`go list -deps ./cmd/app`): no
# test-only passengers, no hand-kept list to rot. Deterministic
# output — module versions only, never local paths.
#
# Fails loud on any module whose license is missing or outside
# the permissive set (MIT, BSD, Apache-2.0): a copyleft
# dependency must break the image build, never slide in quiet.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/LICENSES/THIRD-PARTY.md"
mkdir -p "$ROOT/LICENSES"
MODCACHE="$(go env GOMODCACHE)"

classify() {
	local f="$1"
	if grep -q "Apache License" "$f" && grep -q "Version 2.0" "$f"; then
		if grep -q "MIT License" "$f"; then
			echo "MIT OR Apache-2.0"
		else
			echo "Apache-2.0"
		fi
	elif grep -q "MIT License" "$f" || grep -q "Permission is hereby granted, free of charge" "$f"; then
		echo "MIT"
	elif grep -q "Redistribution and use in source and binary forms" "$f"; then
		echo "BSD"
	else
		echo "OTHER"
	fi
}

mapfile -t MODS < <(go list -f '{{with .Module}}{{.Path}}@{{.Version}}{{end}}' -deps ./cmd/app 2>/dev/null | sort -u | grep -v "^$" | grep -v "^nrtn.dev")

declare -a TABLE=() MIT=() BSD=()
declare -a REFUSALS=()
for mv in "${MODS[@]}"; do
	lf=$(ls "$MODCACHE/$mv"/LICENSE* "$MODCACHE/$mv"/LICENCE* "$MODCACHE/$mv"/COPYING* 2>/dev/null | head -1 || true)
	if [ -z "$lf" ]; then
		REFUSALS+=("$mv: no license file in module")
		continue
	fi
	class="$(classify "$lf")"
	case "$class" in
		Apache-2.0* | "MIT OR Apache-2.0") TABLE+=("| $mv | $class |") ;;
		MIT) TABLE+=("| $mv | MIT |"); MIT+=("$mv|$lf") ;;
		BSD) TABLE+=("| $mv | BSD |"); BSD+=("$mv|$lf") ;;
		*)
			REFUSALS+=("$mv: unrecognized license ($lf)")
			;;
	esac
done

if [ "${#REFUSALS[@]}" -gt 0 ]; then
	echo "licenses.sh refuses:" >&2
	printf '  %s\n' "${REFUSALS[@]}" >&2
	exit 1
fi

{
	echo "# Third-party licenses (generated)"
	echo
	echo "Generated by \`scripts/licenses.sh\` (\`make licenses\`)"
	echo "from the modules linked into \`./cmd/app\` — do not edit"
	echo "by hand. Apache-2.0 texts live once in"
	echo "[Apache-2.0.txt](Apache-2.0.txt); MIT/BSD notices follow"
	echo "in full below."
	echo
	echo "| Module | License |"
	echo "|---|---|"
	printf '%s\n' "${TABLE[@]}"
	echo
	echo "## MIT notices"
	for e in "${MIT[@]:-}"; do
		mv="${e%%|*}"
		lf="${e#*|}"
		[ -z "$mv" ] && continue
		echo
		echo "### $mv"
		echo
		cat "$lf"
	done
	echo
	echo "## BSD notices"
	for e in "${BSD[@]:-}"; do
		mv="${e%%|*}"
		lf="${e#*|}"
		[ -z "$mv" ] && continue
		echo
		echo "### $mv"
		echo
		cat "$lf"
	done
} > "$OUT"
echo "wrote $OUT (${#MODS[@]} modules)"
